export ZDOTDIR=$HOME

export TERM='xterm-256color'
export LANG="en_US.UTF-8"
export EDITOR=vim

ZSH_THEME="af-magic"

unsetopt SHARE_HISTORY

plugins=(git)

BASE16_SCHEME="default"
BASE16_SHELL="$HOME/.dotfiles/base16/base16-shell/base16-$BASE16_SCHEME.dark.sh"
[[ -s $BASE16_SHELL ]] && . $BASE16_SHELL
source $BASE16_SHELL

# Customize to your needs...
export PATH=$PATH:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:~/bin

if [[ $(uname) == "Darwin" ]]; then
  export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)
  export PATH=$PATH:$JAVA_HOME

  source /usr/local/opt/chruby/share/chruby/chruby.sh
  source /usr/local/opt/chruby/share/chruby/auto.sh
else
  source /usr/local/share/chruby/chruby.sh
  source /usr/local/share/chruby/auto.sh
fi

export TOMCAT_HOME=/Users/christoph/development/apache-tomcat-6.0.29
export BASEDIR=$TOMCAT_HOME
export PATH=$PATH:$TOMCAT_HOME

export PATH=$PATH:$GOPATH/bin

export PATH="$PATH:/usr/local/packer_0.7.5_darwin_amd64"


if [[ $(uname) == "Darwin" ]]; then
  alias ll='ls -lhG'
  alias la='ls -lahG'
else
  alias ll='ls -lh --color=auto'
  alias la='ls -lah --color=auto'
fi
alias pip='nocorrect pip'
alias ga='git add'
alias gs='git status'
alias gd='git diff'
alias gc='git commit'
alias gca='git commit -a'
alias gl='git log --graph --decorate --pretty=oneline --abbrev-commit master'

alias tac='tail -r'
alias pu='vendor/bin/phpunit'
alias be='bundle exec'
alias bower=~/node_modules/bower/bin/bower
alias gradlew='./gradlew'

function mcd() { mkdir -p $1 && cd $1 } # from @garybernhardt


autoload -U compinit && compinit
zmodload -i zsh/complist

setopt PROMPT_SUBST
source ~/.dotfiles/zsh/git-prompt.sh
export GIT_PS1_SHOWDIRTYSTATE=1

autoload -U colors  && colors
PROMPT='%F{237}------------------------------------------------------------%f
%F{033}%~\
$(__git_ps1 " (%s)") \
%F{004}%(!.#.»)%f '

RPROMPT=''


# configure vi mode
bindkey -v
export KEYTIMEOUT=1

bindkey '^P' up-history
bindkey '^N' down-history
bindkey '^w' backward-kill-word
bindkey '^r' history-incremental-search-backward

function zle-line-init zle-keymap-select {
  RPS1="%F{237}[${${KEYMAP/vicmd/normal}/(main|viins)/insert}]%f"
  RPS2=$RPS1
  zle reset-prompt
}

zle -N zle-line-init
zle -N zle-keymap-select

for private_environment in $HOME/.dotfiles/zsh/private*; do
  source $private_environment
done
